### ISSUE TITLE
Export doesn't work 

### ISSUE THREAD

**Issue by marekpow** [claws/dump1090-exporter#34]
I installed pip install dump1090exporter, but I have an error:

![image](https://user-images.githubusercontent.com/7034666/134544255-2c782b79-2058-4215-908d-cdd7fd33fd9b.png)

PS: exporter stops working. I don't know why. One week ago, it worked perfectly. I reinstalled ubuntu from scratch and tried to install exporter again but without success.

**Comment by marekpow** [comment]
My environment:
Ubuntu 20.04 LTS, 
Python: pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)

**Comment by claws** [comment]
Looks like I need to pin the requirement to the older version of aioprometheus or update. I'll look into it.

**Comment by marekpow** [comment]
Could you please give me the approximate time horizon when improvement will be ready to get?

**Comment by claws** [comment]
I'll look into it tonight. Shouldn't be too hard to resolve.
 
If you need to get your environment going ASAP you can downgrade the aioprometheus dependency to 21.8.0 as a workaround. Do do this you should run ``pip install aioprometheus==21.8.0`` after installing dump1090-exporter which should downgrade aioprometheus from 21.9.0 to 21.8.0.

**Comment by marekpow** [comment]
Ok, thanks.

**Comment by marekpow** [comment]
The problem with aiprometheus was solved, but there is another error. 

![image](https://user-images.githubusercontent.com/7034666/135135112-e953aef8-ad25-4922-8dba-a8d0f8ca0fe5.png)

I have Flightaware installed

![image](https://user-images.githubusercontent.com/7034666/135135397-1988a1f4-3d23-48f6-8410-f09373e82fe7.png)

A week ago it works perfectly so I assume there is a problem in dum1090exporter or in aioprometheus library.

**Comment by claws** [comment]
I have attempted to perform a quick fix for the issue which I have released as version 21.9.0. Please give it a try and let me know if it resolves your issue. I'll follow it up with a larger change that updates the package to use the new version of aioprometheus.

**Comment by marekpow** [comment]
Still the same problem

![image](https://user-images.githubusercontent.com/7034666/135326655-daae0ade-f25e-4ff3-83a5-0e891aa68c74.png)

How to reproduce.
1. I created a new instance of Ubuntu 20.04 LTS.
2. I installed Flightaware, and next checked that it is running on port 8080 from a remote computer. After that I rebooted Ubuntu machine.
3. I installed exporter: sudo pip install dump1090exporter. Above error.

**Comment by marekpow** [comment]
Still the same problem.

**Comment by claws** [comment]
Could you run again with the "--debug" flag. Any output might help diagnose
the issue.

**Comment by claws** [comment]
Can you confirm that dump1090-exporter and FlightAware are running on the same computer? In some of your comments you mention a remote computer so I just want to clarify that you are running the ``dump1090-exporter`` command on the same computer that FlightAware is running on.

If both applications are running on the same machine then the next thing to try will be to explicitly define the resource path such as ``$ dump1090exporter --resource-path http://192.168.0.120:8080/data --debug``. Perhaps your FlightAware is not available from the default 'localhost' address but only from a public IP address. This would depend on how you've configured FlightAware.

**Comment by marekpow** [comment]
OMG, I forgot to add parameters, sorry.

All it works perfectly now.

Thank you so much for your assistance

Marek

**Comment by claws** [comment]
Great.
